### PR TITLE
CSS Fix and File Format Change

### PR DESCRIPTION
**Pull request by codewizard1975**
The following changes are being submitted:

- Removed fixed height from left sidebar camera cell
  - Original was set for 16:9 based camera image as was discovered from fixed height in CSS
  - Most IP cameras support 16:9 and 4:3 resolutions
- Changed recorded file format to MKV from MP4
  - This allows for better error handling in case of video interruption during writing
  - Also allows for real-time playback of current recording instead of waiting for file write completion

### CODE REVIEW

**Comment by marcus-j-davies** [comment]
HI @codewizard1975 

Thanks for your contribution, I will check this out soon.

**Comment by marcus-j-davies** [comment]
Hi @codewizard1975 
Can the MKV files still be viewed from a web browser using the standard video tag?

**Comment by codewizard1975** [comment]
My testing showed it played back in the browser just fine, tested on Firefox and Brave (Chrome) with no issues experienced.

**Comment by marcus-j-davies** [comment]
Cool!

Will aim to have a maintenance run with this module in the next week or so, so will look to merge these changes.

**Comment by KeithHanson** [comment]
+1 for MKV :) Very useful for security footage in general. Great to hear it played back via video tag so easily!

**Comment by marcus-j-davies** [comment]
@codewizard1975 

The project is undergoing some review - the aim is to make it more robust one of which involves moving to MKV (pending test results).

This leaves just the UI edits you provided (Thank you). - However, I will at this point terminate the PR, but I will be looking at the edits again, at the end of my review exercise.

At this stage - I thank you

**Pull request closed without merging**
